version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  consumer-analytics:
    build:
      context: ./consumer-analytics
    ports:
      - "3003:3003"
    depends_on:
      - kafka
      
  consumer-notifications:
  build:
    context: ./consumer-notifications
  depends_on:
    - kafka
  environment:
    - KAFKA_BROKER=localhost:9092
    - KAFKA_TOPIC=movie-events
    - EMAIL_HOST=smtp.gmail.com
    - EMAIL_PORT=587
    - EMAIL_USER=tu_correo@gmail.com
    - EMAIL_PASSWORD=tu_contraseña

  consumer-database:
    build:
      context: ./consumer-database
    depends_on:
      - kafka
      - database
    environment:
      - KAFKA_BROKER=localhost:9092
      - KAFKA_TOPIC=movie-events
      - DB_HOST=database
      - DB_NAME=movies_db
      - DB_USER=root
      - DB_PASSWORD=password

  database:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movies_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  volumes:
    db_data:

