version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.36:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: movie-events
      PRODUCER_PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
      - kafka

  consumer-analytics:
    build:
      context: ./consumer-analytics
      dockerfile: Dockerfile
    container_name: consumer-analytics
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: movie-events
      SOCKET_SERVER_PORT: 3003
    ports:
      - "3003:3003"
    depends_on:
      - kafka

  consumer-notifications:
    build:
      context: ./consumer-notifications
      dockerfile: Dockerfile
    container_name: consumer-notifications
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: movie-events
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: jhoncastrom28@gmail.com
      SMTP_PASSWORD: fnhn ocwt hphu hsko
      SMTP_FROM_EMAIL: jhoncastrom28@gmail.com
      NOTIFICATIONS_PORT: 3004
    ports:
      - "3004:3004"
    depends_on:
      - kafka