version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.50:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    ports:
      - "9092:9092"

  producer:
    build:
      context: ./producer
    container_name: movie-producer
    environment:
      - KAFKA_BROKERS=192.168.1.50:9092
      - KAFKA_TOPIC=movie-events
      - PRODUCER_PORT=3002
    networks:
      - kafka-network
    ports:
      - "3002:3002"

  consumer-analytics:
    build:
      context: ./consumer-analytics
    container_name: consumer-analytics
    environment:
      - KAFKA_BROKERS=192.168.1.50:9092
      - KAFKA_TOPIC=movie-events
      - SOCKET_SERVER_PORT=3003
    networks:
      - kafka-network
    ports:
      - "3003:3003"

  consumer-notifications:
    build:
      context: ./consumer-notifications
    container_name: consumer-notifications
    environment:
      - KAFKA_BROKER=192.168.1.50:9092
      - KAFKA_TOPIC=movie-events
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=tu_correo@gmail.com
      - SMTP_PASSWORD=tu_contraseña
      - SMTP_FROM_EMAIL=tu_correo@gmail.com
      - NOTIFICATIONS_PORT=3004
    networks:
      - kafka-network
    ports:
      - "3004:3004"

networks:
  kafka-network:
    driver: bridge