version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/my.cnf:/etc/mysql/my.cnf
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_data:/var/lib/mysql
    networks:
      - kafka-net

  producer:
    build:
      context: ./producer
    container_name: producer
    ports:
      - "3002:3002"
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - PRODUCER_PORT=${PRODUCER_PORT}
    networks:
      - kafka-net

  consumer-analytics:
    build:
      context: ./consumer-analytics
    container_name: consumer-analytics
    ports:
      - "3003:3003"
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - SOCKET_SERVER_PORT=${SOCKET_SERVER_PORT}
    networks:
      - kafka-net

  consumer-notifications:
    build:
      context: ./consumer-notifications
    container_name: consumer-notifications
    ports:
      - "3004:3004"
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - NOTIFICATIONS_PORT=${NOTIFICATIONS_PORT}
    networks:
      - kafka-net

  consumer-database:
    build:
      context: ./consumer-database
    container_name: consumer-database
    ports:
      - "3005:3005"
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CONSUMER_DATABASE_PORT=${CONSUMER_DATABASE_PORT}
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  database_data: